Move include of SDL_syswm.h below include of windows.h:
Fix "error C2338: Windows headers require the default packing option" with Visual Studio 2019 due to packing being changed in SDL_syswm.h.