Use -fstack-protector-all on MinGW:
The formerly used -fstack-protector-strong causes linker errors with every object file:

- undefined reference to `__stack_chk_guard'
- undefined reference to `__stack_chk_fail'